config/routes.rb
PennStudyScheduler::Application.routes.draw do
  resources :uploads
  resources :registrations do
    post 'registrations' => 'registrations#upload'
  end
  get "home/index"
  root :to => 'home#index'
  resources :courses do
    resources :study_sessions do
      resources :invitations
    end
  end
  devise_for :users

end

app/models/study_session.rb
class StudySession < ActiveRecord::Base
  belongs_to :course
  has_many :invitations
  has_many :users, :through => :invitations
  validates :course_id, :presence => true
  validates :location, :presence => true  
end

app/controllers/study_sessions_controller.rb
class StudySessionsController < ApplicationController
  # GET /study_sessions
  # GET /study_sessions.json
  def index
    @study_sessions = StudySession.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @study_sessions }
    end
  end

  # GET /study_sessions/1
  # GET /study_sessions/1.json
  def show
    @study_session = StudySession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @study_session }
    end
  end

  # GET /study_sessions/new
  # GET /study_sessions/new.json
  def new
    @course = Course.find(params[:course_id])
    @study_session = StudySession.new
    # @study_session.update_attributes(:course_id => @course.id)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @study_session }
    end
  end

  # GET /study_sessions/1/edit
  def edit
    @study_session = StudySession.find(params[:id])
  end

  # POST /study_sessions
  # POST /study_sessions.json
  def create
    @course = Course.find(params[:course_id])
    @study_session = StudySession.new(params[:study_session])
    @study_session.update_attributes(:course_id => @course.id)
    
    @invitation = Invitation.new({:user_id => current_user.id, 
      :study_session_id => @study_session.id})
    @invitation.save

    respond_to do |format|
      if @study_session.save
        format.html { redirect_to [@study_session.course, @study_session], notice: 'Study session was successfully created.' }
        format.json { render json: @study_session.id, status: :created, location: @study_session }
      else
        format.html { render action: "new" }
        format.json { render json: @study_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /study_sessions/1
  # PUT /study_sessions/1.json
  def update
    @study_session = StudySession.find(params[:study_session])

    respond_to do |format|
      if @study_session.update_attributes(params[:study_session])
        format.html { redirect_to [@study_session.course, @study_session], notice: 'Study session was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @study_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /study_sessions/1
  # DELETE /study_sessions/1.json
  def destroy
    @study_session = StudySession.find(params[:id])
    @study_session.destroy

    respond_to do |format|
      format.html { redirect_to study_sessions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/study_sessions_helper.rb
module StudySessionsHelper
end

app/views/study_sessions/_form.html.erb
<% if user_signed_in? %>

<%= form_for [@course, @study_session] do |f| %>
  <% if @study_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@study_session.errors.count, "error") %> prohibited this study_session from being saved:</h2>

      <ul>
      <% @study_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :course_id, :value => @course.id %>
  </div>
  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %><br>
  </div>
  <div class="field">
    <%= f.label :time %>
    <%= f.time_select :time %><br>
  </div>
  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %><br><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/study_sessions/edit.html.erb
<h1>Editing study_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @study_session %> |
<%= link_to 'Back', study_sessions_path %>

app/views/study_sessions/index.html.erb
<h1>Your Study Sessions</h1>

<table>
  <tr>
    <th>Course</th>
    <th>Date</th>
    <th>Time</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% current_user.study_sessions.each do |study_session| %>
  <tr>
    <td><%= link_to study_session.course.abbrev, course_path(study_session.course) %></td>
    <td><%= study_session.date %></td>
    <td><%= study_session.time %></td>
    <td><%= study_session.location %></td>
  </tr>
<% end %>
</table>

<br />

app/views/study_sessions/new.html.erb
<h1>Create a Study Session</h1>

<%= render 'form' %>

<%= link_to 'Back', course_study_sessions_path %>

app/views/study_sessions/show.html.erb
<p>
  <b>Course:</b>
  <%= @study_session.course.abbrev %>
</p>

<p>
  <b>Date:</b>
  <%= @study_session.date %>
</p>

<p>
  <b>Time:</b>
  <%= @study_session.time %>
</p>

<p>
  <b>Location:</b>
  <%= @study_session.location %>
</p>

<p>
  <b>People Invited:</b>
  <% @study_session.users.each do |user| %>
  <% name = user.first_name + " " + user.last_name %>
  <br><%= name %>
  <% end %>
</p>

<%= link_to 'Invite People to this Event', new_course_study_session_invitation_path(@study_session.course, @study_session) %>
<br>
<%= link_to 'Edit', edit_course_study_session_path(@study_session) %> |
<%= link_to 'Back', course_study_sessions_path %>