config/routes.rb
PennStudyScheduler::Application.routes.draw do
  resources :uploads
  resources :registrations do
    post 'registrations' => 'registrations#upload'
  end
  get "home/index"
  root :to => 'home#index'
  resources :courses do
    resources :study_sessions do
      resources :invitations
    end
  end
  devise_for :users

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :study_session
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.json
  def new
    @course = Course.find(params[:course_id])
    @study_session = StudySession.find(params[:study_session_id])
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.json
  def create
    @course = Course.find(params[:course_id])
    @study_session = StudySession.find(params[:study_session_id])
    
    @invitation = Invitation.new(params[:invitation])
    @invitation.update_attributes(:study_session_id => @study_session.id)
    
    @u = User.find(params[:invitation][:user_id])
    alreadyThere = @study_session.users.find(@u).nil?
    
    respond_to do |format|
      if alreadyThere
        format.html { redirect_to new_course_study_session_invitation_path(@study_session.course, @study_session), notice: 'This person was already invited to the study session' }
        format.json { render json: "This person was already invited to the study session", status: :unprocessable_entity }
      elsif @invitation.save
	    Notifications.new_invitation(@invitation).deliver
        format.html { redirect_to [@invitation.study_session.course, @invitation.study_session], notice: 'Invitation was successfully created.' }
        format.json { render json: @invitation.id, status: :created, location: @invitation }
      else
        format.html { render action: "new" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.json
  def update
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to invitations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for([@course, @study_session, @invitation]) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %>
    <%= f.collection_select :user_id, @course.users.sort_by {|u| u.full_name}, 
      :id, :full_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing invitation</h1>

<%= render 'form' %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>User</th>
    <th>Study Session</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.user %></td>
    <td><%= invitation.study_session.course.abbrev %></td>
    <td><%= link_to 'Show', invitation %></td>
    <td><%= link_to 'Destroy', invitation, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>New invitation</h1>

<%= render 'form' %>

<%= link_to 'Back', course_study_session_invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @invitation.user %>
</p>

<p>
  <b>Study Session:</b>
  <%= @invitation.study_session %>
</p>


<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>