config/routes.rb
PennStudyScheduler::Application.routes.draw do
  resources :uploads
  resources :registrations do
    post 'registrations' => 'registrations#upload'
  end
  get "home/index"
  root :to => 'home#index'
  resources :courses do
    resources :study_sessions do
      resources :invitations
    end
  end
  devise_for :users

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :user
  validates :schedule_file_name, :presence => true 
end

app/controllers/uploads_controller.rb
include Icalendar

class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])
    @upload.save
    i = params[:upload].delete("user_id")
    @user = User.find(i)
    @user.registrations.each do |r|
      r.destroy
    end
    cal_file = File.open(params[:schedule].tempfile.path)
    
    cals = Icalendar.parse(cal_file)
    cal = cals.first
    events = cal.events
    checked_events = Array.new
    events.each do |e| 
      name = e.summary
      if !checked_events.include?(name)
        checked_events << name
        dept = name[0..3].strip
        secondpart = name[4..9]
        number = secondpart[0..2]
        number = Integer(number)
        section = secondpart[3..5]
        @old_course = Course.find_by_department_and_number_and_section(dept, number, section)
        if @old_course == nil
              @course = Course.new(:department => dept, :number => number, :section => section)
              @registration = Registration.new({:user => @user, :course => nil})
                    if @course.save && @registration.save
                      puts 'saved'
                      @registration.update_attributes(:course => @course)
                    end
        else
          @registration=Registration.new({:user => @user, :course => nil})
          if @registration.save
            @registration.update_attributes(:course => @old_course)
          end
        end
      end
     end  
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to registrations_path, notice: 'Schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
   end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= form_for(@upload, :html => {:multipart => true}) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag 'schedule' %>
    <%= file_field_tag 'schedule' %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @uploads.each do |upload| %>
  <tr>
    <td><%= link_to 'Show', upload %></td>
    <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
    <td><%= link_to 'Destroy', upload, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', registrations_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>